// app/_services/ArchiveServices.js
import { db } from "../utils/firebase";
import { 
  collection, 
  getDocs, 
  addDoc, 
  query, 
  where,
  and
} from "firebase/firestore";

/**
 * Adds a new production to the database
 */
export const addProduction = async (prodData) => {
  try {
    // Check if production with TITLE and SEASON already exists
    const q = query(
      collection(db, "productions"), 
      where("title", "==", prodData.title),
      where("season", "==", prodData.season)
    );
    
    const querySnapshot = await getDocs(q);
    if (!querySnapshot.empty) {
      throw new Error("This production already exists for the selected season.");
    }

    // Unique ID is generated by addDoc automatically
    const docRef = await addDoc(collection(db, "productions"), {
      ...prodData,
      createdAt: new Date()
    });
    
    return { id: docRef.id, error: null };
  } catch (error) {
    return { id: null, error: error.message };
  }
};

// Logic for fetching seasons for the dropdown
export const getSeasons = async () => {
  const querySnapshot = await getDocs(collection(db, "seasons"));
  return querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
};